FROM node:22.15.0

WORKDIR /home/node
COPY ./ /home/node

RUN npm install -g npm@10.9.2
RUN yarn install

ENV NODE_ENV development

# Expose the listening port of your app
EXPOSE 3000

USER node
CMD [ "yarn", "start:dev" ]